name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

    - uses: taiki-e/install-action@cargo-llvm-cov
    - name: Run tests
      run: cargo llvm-cov --lcov --output-path coveralls.cov --lib test

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.4
      with:
        format: lcov
        file: coveralls.cov
